// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInstanceDomainAllowsGetParams creates a new InstanceDomainAllowsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInstanceDomainAllowsGetParams() *InstanceDomainAllowsGetParams {
	return &InstanceDomainAllowsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInstanceDomainAllowsGetParamsWithTimeout creates a new InstanceDomainAllowsGetParams object
// with the ability to set a timeout on a request.
func NewInstanceDomainAllowsGetParamsWithTimeout(timeout time.Duration) *InstanceDomainAllowsGetParams {
	return &InstanceDomainAllowsGetParams{
		timeout: timeout,
	}
}

// NewInstanceDomainAllowsGetParamsWithContext creates a new InstanceDomainAllowsGetParams object
// with the ability to set a context for a request.
func NewInstanceDomainAllowsGetParamsWithContext(ctx context.Context) *InstanceDomainAllowsGetParams {
	return &InstanceDomainAllowsGetParams{
		Context: ctx,
	}
}

// NewInstanceDomainAllowsGetParamsWithHTTPClient creates a new InstanceDomainAllowsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewInstanceDomainAllowsGetParamsWithHTTPClient(client *http.Client) *InstanceDomainAllowsGetParams {
	return &InstanceDomainAllowsGetParams{
		HTTPClient: client,
	}
}

/*
InstanceDomainAllowsGetParams contains all the parameters to send to the API endpoint

	for the instance domain allows get operation.

	Typically these are written to a http.Request.
*/
type InstanceDomainAllowsGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the instance domain allows get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstanceDomainAllowsGetParams) WithDefaults() *InstanceDomainAllowsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the instance domain allows get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstanceDomainAllowsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) WithTimeout(timeout time.Duration) *InstanceDomainAllowsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) WithContext(ctx context.Context) *InstanceDomainAllowsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) WithHTTPClient(client *http.Client) *InstanceDomainAllowsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instance domain allows get params
func (o *InstanceDomainAllowsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InstanceDomainAllowsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
