// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owu-one/gotosocial-sdk/models"
)

// InstanceDomainBlocksGetReader is a Reader for the InstanceDomainBlocksGet structure.
type InstanceDomainBlocksGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceDomainBlocksGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstanceDomainBlocksGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewInstanceDomainBlocksGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewInstanceDomainBlocksGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewInstanceDomainBlocksGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewInstanceDomainBlocksGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewInstanceDomainBlocksGetNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewInstanceDomainBlocksGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/instance/domain_blocks] instanceDomainBlocksGet", response, response.Code())
	}
}

// NewInstanceDomainBlocksGetOK creates a InstanceDomainBlocksGetOK with default headers values
func NewInstanceDomainBlocksGetOK() *InstanceDomainBlocksGetOK {
	return &InstanceDomainBlocksGetOK{}
}

/*
InstanceDomainBlocksGetOK describes a response with status code 200, with default header values.

List of blocked domains.
*/
type InstanceDomainBlocksGetOK struct {
	Payload []*models.Domain
}

// IsSuccess returns true when this instance domain blocks get o k response has a 2xx status code
func (o *InstanceDomainBlocksGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this instance domain blocks get o k response has a 3xx status code
func (o *InstanceDomainBlocksGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get o k response has a 4xx status code
func (o *InstanceDomainBlocksGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance domain blocks get o k response has a 5xx status code
func (o *InstanceDomainBlocksGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get o k response a status code equal to that given
func (o *InstanceDomainBlocksGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the instance domain blocks get o k response
func (o *InstanceDomainBlocksGetOK) Code() int {
	return 200
}

func (o *InstanceDomainBlocksGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetOK %s", 200, payload)
}

func (o *InstanceDomainBlocksGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetOK %s", 200, payload)
}

func (o *InstanceDomainBlocksGetOK) GetPayload() []*models.Domain {
	return o.Payload
}

func (o *InstanceDomainBlocksGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstanceDomainBlocksGetBadRequest creates a InstanceDomainBlocksGetBadRequest with default headers values
func NewInstanceDomainBlocksGetBadRequest() *InstanceDomainBlocksGetBadRequest {
	return &InstanceDomainBlocksGetBadRequest{}
}

/*
InstanceDomainBlocksGetBadRequest describes a response with status code 400, with default header values.

bad request
*/
type InstanceDomainBlocksGetBadRequest struct {
}

// IsSuccess returns true when this instance domain blocks get bad request response has a 2xx status code
func (o *InstanceDomainBlocksGetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get bad request response has a 3xx status code
func (o *InstanceDomainBlocksGetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get bad request response has a 4xx status code
func (o *InstanceDomainBlocksGetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain blocks get bad request response has a 5xx status code
func (o *InstanceDomainBlocksGetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get bad request response a status code equal to that given
func (o *InstanceDomainBlocksGetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the instance domain blocks get bad request response
func (o *InstanceDomainBlocksGetBadRequest) Code() int {
	return 400
}

func (o *InstanceDomainBlocksGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetBadRequest", 400)
}

func (o *InstanceDomainBlocksGetBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetBadRequest", 400)
}

func (o *InstanceDomainBlocksGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainBlocksGetUnauthorized creates a InstanceDomainBlocksGetUnauthorized with default headers values
func NewInstanceDomainBlocksGetUnauthorized() *InstanceDomainBlocksGetUnauthorized {
	return &InstanceDomainBlocksGetUnauthorized{}
}

/*
InstanceDomainBlocksGetUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type InstanceDomainBlocksGetUnauthorized struct {
}

// IsSuccess returns true when this instance domain blocks get unauthorized response has a 2xx status code
func (o *InstanceDomainBlocksGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get unauthorized response has a 3xx status code
func (o *InstanceDomainBlocksGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get unauthorized response has a 4xx status code
func (o *InstanceDomainBlocksGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain blocks get unauthorized response has a 5xx status code
func (o *InstanceDomainBlocksGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get unauthorized response a status code equal to that given
func (o *InstanceDomainBlocksGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the instance domain blocks get unauthorized response
func (o *InstanceDomainBlocksGetUnauthorized) Code() int {
	return 401
}

func (o *InstanceDomainBlocksGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetUnauthorized", 401)
}

func (o *InstanceDomainBlocksGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetUnauthorized", 401)
}

func (o *InstanceDomainBlocksGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainBlocksGetForbidden creates a InstanceDomainBlocksGetForbidden with default headers values
func NewInstanceDomainBlocksGetForbidden() *InstanceDomainBlocksGetForbidden {
	return &InstanceDomainBlocksGetForbidden{}
}

/*
InstanceDomainBlocksGetForbidden describes a response with status code 403, with default header values.

forbidden
*/
type InstanceDomainBlocksGetForbidden struct {
}

// IsSuccess returns true when this instance domain blocks get forbidden response has a 2xx status code
func (o *InstanceDomainBlocksGetForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get forbidden response has a 3xx status code
func (o *InstanceDomainBlocksGetForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get forbidden response has a 4xx status code
func (o *InstanceDomainBlocksGetForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain blocks get forbidden response has a 5xx status code
func (o *InstanceDomainBlocksGetForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get forbidden response a status code equal to that given
func (o *InstanceDomainBlocksGetForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the instance domain blocks get forbidden response
func (o *InstanceDomainBlocksGetForbidden) Code() int {
	return 403
}

func (o *InstanceDomainBlocksGetForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetForbidden", 403)
}

func (o *InstanceDomainBlocksGetForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetForbidden", 403)
}

func (o *InstanceDomainBlocksGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainBlocksGetNotFound creates a InstanceDomainBlocksGetNotFound with default headers values
func NewInstanceDomainBlocksGetNotFound() *InstanceDomainBlocksGetNotFound {
	return &InstanceDomainBlocksGetNotFound{}
}

/*
InstanceDomainBlocksGetNotFound describes a response with status code 404, with default header values.

not found
*/
type InstanceDomainBlocksGetNotFound struct {
}

// IsSuccess returns true when this instance domain blocks get not found response has a 2xx status code
func (o *InstanceDomainBlocksGetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get not found response has a 3xx status code
func (o *InstanceDomainBlocksGetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get not found response has a 4xx status code
func (o *InstanceDomainBlocksGetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain blocks get not found response has a 5xx status code
func (o *InstanceDomainBlocksGetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get not found response a status code equal to that given
func (o *InstanceDomainBlocksGetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the instance domain blocks get not found response
func (o *InstanceDomainBlocksGetNotFound) Code() int {
	return 404
}

func (o *InstanceDomainBlocksGetNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetNotFound", 404)
}

func (o *InstanceDomainBlocksGetNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetNotFound", 404)
}

func (o *InstanceDomainBlocksGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainBlocksGetNotAcceptable creates a InstanceDomainBlocksGetNotAcceptable with default headers values
func NewInstanceDomainBlocksGetNotAcceptable() *InstanceDomainBlocksGetNotAcceptable {
	return &InstanceDomainBlocksGetNotAcceptable{}
}

/*
InstanceDomainBlocksGetNotAcceptable describes a response with status code 406, with default header values.

not acceptable
*/
type InstanceDomainBlocksGetNotAcceptable struct {
}

// IsSuccess returns true when this instance domain blocks get not acceptable response has a 2xx status code
func (o *InstanceDomainBlocksGetNotAcceptable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get not acceptable response has a 3xx status code
func (o *InstanceDomainBlocksGetNotAcceptable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get not acceptable response has a 4xx status code
func (o *InstanceDomainBlocksGetNotAcceptable) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain blocks get not acceptable response has a 5xx status code
func (o *InstanceDomainBlocksGetNotAcceptable) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain blocks get not acceptable response a status code equal to that given
func (o *InstanceDomainBlocksGetNotAcceptable) IsCode(code int) bool {
	return code == 406
}

// Code gets the status code for the instance domain blocks get not acceptable response
func (o *InstanceDomainBlocksGetNotAcceptable) Code() int {
	return 406
}

func (o *InstanceDomainBlocksGetNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetNotAcceptable", 406)
}

func (o *InstanceDomainBlocksGetNotAcceptable) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetNotAcceptable", 406)
}

func (o *InstanceDomainBlocksGetNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainBlocksGetInternalServerError creates a InstanceDomainBlocksGetInternalServerError with default headers values
func NewInstanceDomainBlocksGetInternalServerError() *InstanceDomainBlocksGetInternalServerError {
	return &InstanceDomainBlocksGetInternalServerError{}
}

/*
InstanceDomainBlocksGetInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type InstanceDomainBlocksGetInternalServerError struct {
}

// IsSuccess returns true when this instance domain blocks get internal server error response has a 2xx status code
func (o *InstanceDomainBlocksGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain blocks get internal server error response has a 3xx status code
func (o *InstanceDomainBlocksGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain blocks get internal server error response has a 4xx status code
func (o *InstanceDomainBlocksGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance domain blocks get internal server error response has a 5xx status code
func (o *InstanceDomainBlocksGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this instance domain blocks get internal server error response a status code equal to that given
func (o *InstanceDomainBlocksGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the instance domain blocks get internal server error response
func (o *InstanceDomainBlocksGetInternalServerError) Code() int {
	return 500
}

func (o *InstanceDomainBlocksGetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetInternalServerError", 500)
}

func (o *InstanceDomainBlocksGetInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_blocks][%d] instanceDomainBlocksGetInternalServerError", 500)
}

func (o *InstanceDomainBlocksGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
