// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInstanceDomainBlocksGetParams creates a new InstanceDomainBlocksGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInstanceDomainBlocksGetParams() *InstanceDomainBlocksGetParams {
	return &InstanceDomainBlocksGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInstanceDomainBlocksGetParamsWithTimeout creates a new InstanceDomainBlocksGetParams object
// with the ability to set a timeout on a request.
func NewInstanceDomainBlocksGetParamsWithTimeout(timeout time.Duration) *InstanceDomainBlocksGetParams {
	return &InstanceDomainBlocksGetParams{
		timeout: timeout,
	}
}

// NewInstanceDomainBlocksGetParamsWithContext creates a new InstanceDomainBlocksGetParams object
// with the ability to set a context for a request.
func NewInstanceDomainBlocksGetParamsWithContext(ctx context.Context) *InstanceDomainBlocksGetParams {
	return &InstanceDomainBlocksGetParams{
		Context: ctx,
	}
}

// NewInstanceDomainBlocksGetParamsWithHTTPClient creates a new InstanceDomainBlocksGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewInstanceDomainBlocksGetParamsWithHTTPClient(client *http.Client) *InstanceDomainBlocksGetParams {
	return &InstanceDomainBlocksGetParams{
		HTTPClient: client,
	}
}

/*
InstanceDomainBlocksGetParams contains all the parameters to send to the API endpoint

	for the instance domain blocks get operation.

	Typically these are written to a http.Request.
*/
type InstanceDomainBlocksGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the instance domain blocks get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstanceDomainBlocksGetParams) WithDefaults() *InstanceDomainBlocksGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the instance domain blocks get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstanceDomainBlocksGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) WithTimeout(timeout time.Duration) *InstanceDomainBlocksGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) WithContext(ctx context.Context) *InstanceDomainBlocksGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) WithHTTPClient(client *http.Client) *InstanceDomainBlocksGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the instance domain blocks get params
func (o *InstanceDomainBlocksGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InstanceDomainBlocksGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
