// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owu-one/gotosocial-sdk/models"
)

// InstanceDomainAllowsGetReader is a Reader for the InstanceDomainAllowsGet structure.
type InstanceDomainAllowsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceDomainAllowsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstanceDomainAllowsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewInstanceDomainAllowsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewInstanceDomainAllowsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewInstanceDomainAllowsGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewInstanceDomainAllowsGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewInstanceDomainAllowsGetNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewInstanceDomainAllowsGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/instance/domain_allows] instanceDomainAllowsGet", response, response.Code())
	}
}

// NewInstanceDomainAllowsGetOK creates a InstanceDomainAllowsGetOK with default headers values
func NewInstanceDomainAllowsGetOK() *InstanceDomainAllowsGetOK {
	return &InstanceDomainAllowsGetOK{}
}

/*
InstanceDomainAllowsGetOK describes a response with status code 200, with default header values.

List of explicitly allowed domains.
*/
type InstanceDomainAllowsGetOK struct {
	Payload []*models.Domain
}

// IsSuccess returns true when this instance domain allows get o k response has a 2xx status code
func (o *InstanceDomainAllowsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this instance domain allows get o k response has a 3xx status code
func (o *InstanceDomainAllowsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get o k response has a 4xx status code
func (o *InstanceDomainAllowsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance domain allows get o k response has a 5xx status code
func (o *InstanceDomainAllowsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get o k response a status code equal to that given
func (o *InstanceDomainAllowsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the instance domain allows get o k response
func (o *InstanceDomainAllowsGetOK) Code() int {
	return 200
}

func (o *InstanceDomainAllowsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetOK %s", 200, payload)
}

func (o *InstanceDomainAllowsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetOK %s", 200, payload)
}

func (o *InstanceDomainAllowsGetOK) GetPayload() []*models.Domain {
	return o.Payload
}

func (o *InstanceDomainAllowsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInstanceDomainAllowsGetBadRequest creates a InstanceDomainAllowsGetBadRequest with default headers values
func NewInstanceDomainAllowsGetBadRequest() *InstanceDomainAllowsGetBadRequest {
	return &InstanceDomainAllowsGetBadRequest{}
}

/*
InstanceDomainAllowsGetBadRequest describes a response with status code 400, with default header values.

bad request
*/
type InstanceDomainAllowsGetBadRequest struct {
}

// IsSuccess returns true when this instance domain allows get bad request response has a 2xx status code
func (o *InstanceDomainAllowsGetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get bad request response has a 3xx status code
func (o *InstanceDomainAllowsGetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get bad request response has a 4xx status code
func (o *InstanceDomainAllowsGetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain allows get bad request response has a 5xx status code
func (o *InstanceDomainAllowsGetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get bad request response a status code equal to that given
func (o *InstanceDomainAllowsGetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the instance domain allows get bad request response
func (o *InstanceDomainAllowsGetBadRequest) Code() int {
	return 400
}

func (o *InstanceDomainAllowsGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetBadRequest", 400)
}

func (o *InstanceDomainAllowsGetBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetBadRequest", 400)
}

func (o *InstanceDomainAllowsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainAllowsGetUnauthorized creates a InstanceDomainAllowsGetUnauthorized with default headers values
func NewInstanceDomainAllowsGetUnauthorized() *InstanceDomainAllowsGetUnauthorized {
	return &InstanceDomainAllowsGetUnauthorized{}
}

/*
InstanceDomainAllowsGetUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type InstanceDomainAllowsGetUnauthorized struct {
}

// IsSuccess returns true when this instance domain allows get unauthorized response has a 2xx status code
func (o *InstanceDomainAllowsGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get unauthorized response has a 3xx status code
func (o *InstanceDomainAllowsGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get unauthorized response has a 4xx status code
func (o *InstanceDomainAllowsGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain allows get unauthorized response has a 5xx status code
func (o *InstanceDomainAllowsGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get unauthorized response a status code equal to that given
func (o *InstanceDomainAllowsGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the instance domain allows get unauthorized response
func (o *InstanceDomainAllowsGetUnauthorized) Code() int {
	return 401
}

func (o *InstanceDomainAllowsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetUnauthorized", 401)
}

func (o *InstanceDomainAllowsGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetUnauthorized", 401)
}

func (o *InstanceDomainAllowsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainAllowsGetForbidden creates a InstanceDomainAllowsGetForbidden with default headers values
func NewInstanceDomainAllowsGetForbidden() *InstanceDomainAllowsGetForbidden {
	return &InstanceDomainAllowsGetForbidden{}
}

/*
InstanceDomainAllowsGetForbidden describes a response with status code 403, with default header values.

forbidden
*/
type InstanceDomainAllowsGetForbidden struct {
}

// IsSuccess returns true when this instance domain allows get forbidden response has a 2xx status code
func (o *InstanceDomainAllowsGetForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get forbidden response has a 3xx status code
func (o *InstanceDomainAllowsGetForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get forbidden response has a 4xx status code
func (o *InstanceDomainAllowsGetForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain allows get forbidden response has a 5xx status code
func (o *InstanceDomainAllowsGetForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get forbidden response a status code equal to that given
func (o *InstanceDomainAllowsGetForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the instance domain allows get forbidden response
func (o *InstanceDomainAllowsGetForbidden) Code() int {
	return 403
}

func (o *InstanceDomainAllowsGetForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetForbidden", 403)
}

func (o *InstanceDomainAllowsGetForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetForbidden", 403)
}

func (o *InstanceDomainAllowsGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainAllowsGetNotFound creates a InstanceDomainAllowsGetNotFound with default headers values
func NewInstanceDomainAllowsGetNotFound() *InstanceDomainAllowsGetNotFound {
	return &InstanceDomainAllowsGetNotFound{}
}

/*
InstanceDomainAllowsGetNotFound describes a response with status code 404, with default header values.

not found
*/
type InstanceDomainAllowsGetNotFound struct {
}

// IsSuccess returns true when this instance domain allows get not found response has a 2xx status code
func (o *InstanceDomainAllowsGetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get not found response has a 3xx status code
func (o *InstanceDomainAllowsGetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get not found response has a 4xx status code
func (o *InstanceDomainAllowsGetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain allows get not found response has a 5xx status code
func (o *InstanceDomainAllowsGetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get not found response a status code equal to that given
func (o *InstanceDomainAllowsGetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the instance domain allows get not found response
func (o *InstanceDomainAllowsGetNotFound) Code() int {
	return 404
}

func (o *InstanceDomainAllowsGetNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetNotFound", 404)
}

func (o *InstanceDomainAllowsGetNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetNotFound", 404)
}

func (o *InstanceDomainAllowsGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainAllowsGetNotAcceptable creates a InstanceDomainAllowsGetNotAcceptable with default headers values
func NewInstanceDomainAllowsGetNotAcceptable() *InstanceDomainAllowsGetNotAcceptable {
	return &InstanceDomainAllowsGetNotAcceptable{}
}

/*
InstanceDomainAllowsGetNotAcceptable describes a response with status code 406, with default header values.

not acceptable
*/
type InstanceDomainAllowsGetNotAcceptable struct {
}

// IsSuccess returns true when this instance domain allows get not acceptable response has a 2xx status code
func (o *InstanceDomainAllowsGetNotAcceptable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get not acceptable response has a 3xx status code
func (o *InstanceDomainAllowsGetNotAcceptable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get not acceptable response has a 4xx status code
func (o *InstanceDomainAllowsGetNotAcceptable) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance domain allows get not acceptable response has a 5xx status code
func (o *InstanceDomainAllowsGetNotAcceptable) IsServerError() bool {
	return false
}

// IsCode returns true when this instance domain allows get not acceptable response a status code equal to that given
func (o *InstanceDomainAllowsGetNotAcceptable) IsCode(code int) bool {
	return code == 406
}

// Code gets the status code for the instance domain allows get not acceptable response
func (o *InstanceDomainAllowsGetNotAcceptable) Code() int {
	return 406
}

func (o *InstanceDomainAllowsGetNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetNotAcceptable", 406)
}

func (o *InstanceDomainAllowsGetNotAcceptable) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetNotAcceptable", 406)
}

func (o *InstanceDomainAllowsGetNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceDomainAllowsGetInternalServerError creates a InstanceDomainAllowsGetInternalServerError with default headers values
func NewInstanceDomainAllowsGetInternalServerError() *InstanceDomainAllowsGetInternalServerError {
	return &InstanceDomainAllowsGetInternalServerError{}
}

/*
InstanceDomainAllowsGetInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type InstanceDomainAllowsGetInternalServerError struct {
}

// IsSuccess returns true when this instance domain allows get internal server error response has a 2xx status code
func (o *InstanceDomainAllowsGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance domain allows get internal server error response has a 3xx status code
func (o *InstanceDomainAllowsGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance domain allows get internal server error response has a 4xx status code
func (o *InstanceDomainAllowsGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance domain allows get internal server error response has a 5xx status code
func (o *InstanceDomainAllowsGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this instance domain allows get internal server error response a status code equal to that given
func (o *InstanceDomainAllowsGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the instance domain allows get internal server error response
func (o *InstanceDomainAllowsGetInternalServerError) Code() int {
	return 500
}

func (o *InstanceDomainAllowsGetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetInternalServerError", 500)
}

func (o *InstanceDomainAllowsGetInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/instance/domain_allows][%d] instanceDomainAllowsGetInternalServerError", 500)
}

func (o *InstanceDomainAllowsGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
