// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTwoFactorQRCodePngGetParams creates a new TwoFactorQRCodePngGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTwoFactorQRCodePngGetParams() *TwoFactorQRCodePngGetParams {
	return &TwoFactorQRCodePngGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTwoFactorQRCodePngGetParamsWithTimeout creates a new TwoFactorQRCodePngGetParams object
// with the ability to set a timeout on a request.
func NewTwoFactorQRCodePngGetParamsWithTimeout(timeout time.Duration) *TwoFactorQRCodePngGetParams {
	return &TwoFactorQRCodePngGetParams{
		timeout: timeout,
	}
}

// NewTwoFactorQRCodePngGetParamsWithContext creates a new TwoFactorQRCodePngGetParams object
// with the ability to set a context for a request.
func NewTwoFactorQRCodePngGetParamsWithContext(ctx context.Context) *TwoFactorQRCodePngGetParams {
	return &TwoFactorQRCodePngGetParams{
		Context: ctx,
	}
}

// NewTwoFactorQRCodePngGetParamsWithHTTPClient creates a new TwoFactorQRCodePngGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewTwoFactorQRCodePngGetParamsWithHTTPClient(client *http.Client) *TwoFactorQRCodePngGetParams {
	return &TwoFactorQRCodePngGetParams{
		HTTPClient: client,
	}
}

/*
TwoFactorQRCodePngGetParams contains all the parameters to send to the API endpoint

	for the two factor q r code png get operation.

	Typically these are written to a http.Request.
*/
type TwoFactorQRCodePngGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the two factor q r code png get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TwoFactorQRCodePngGetParams) WithDefaults() *TwoFactorQRCodePngGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the two factor q r code png get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TwoFactorQRCodePngGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) WithTimeout(timeout time.Duration) *TwoFactorQRCodePngGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) WithContext(ctx context.Context) *TwoFactorQRCodePngGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) WithHTTPClient(client *http.Client) *TwoFactorQRCodePngGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the two factor q r code png get params
func (o *TwoFactorQRCodePngGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *TwoFactorQRCodePngGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
