// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTwoFactorDisablePostParams creates a new TwoFactorDisablePostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTwoFactorDisablePostParams() *TwoFactorDisablePostParams {
	return &TwoFactorDisablePostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTwoFactorDisablePostParamsWithTimeout creates a new TwoFactorDisablePostParams object
// with the ability to set a timeout on a request.
func NewTwoFactorDisablePostParamsWithTimeout(timeout time.Duration) *TwoFactorDisablePostParams {
	return &TwoFactorDisablePostParams{
		timeout: timeout,
	}
}

// NewTwoFactorDisablePostParamsWithContext creates a new TwoFactorDisablePostParams object
// with the ability to set a context for a request.
func NewTwoFactorDisablePostParamsWithContext(ctx context.Context) *TwoFactorDisablePostParams {
	return &TwoFactorDisablePostParams{
		Context: ctx,
	}
}

// NewTwoFactorDisablePostParamsWithHTTPClient creates a new TwoFactorDisablePostParams object
// with the ability to set a custom HTTPClient for a request.
func NewTwoFactorDisablePostParamsWithHTTPClient(client *http.Client) *TwoFactorDisablePostParams {
	return &TwoFactorDisablePostParams{
		HTTPClient: client,
	}
}

/*
TwoFactorDisablePostParams contains all the parameters to send to the API endpoint

	for the two factor disable post operation.

	Typically these are written to a http.Request.
*/
type TwoFactorDisablePostParams struct {

	/* Password.

	   User's current password, for verification.
	*/
	Password *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the two factor disable post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TwoFactorDisablePostParams) WithDefaults() *TwoFactorDisablePostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the two factor disable post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TwoFactorDisablePostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the two factor disable post params
func (o *TwoFactorDisablePostParams) WithTimeout(timeout time.Duration) *TwoFactorDisablePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the two factor disable post params
func (o *TwoFactorDisablePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the two factor disable post params
func (o *TwoFactorDisablePostParams) WithContext(ctx context.Context) *TwoFactorDisablePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the two factor disable post params
func (o *TwoFactorDisablePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the two factor disable post params
func (o *TwoFactorDisablePostParams) WithHTTPClient(client *http.Client) *TwoFactorDisablePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the two factor disable post params
func (o *TwoFactorDisablePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPassword adds the password to the two factor disable post params
func (o *TwoFactorDisablePostParams) WithPassword(password *string) *TwoFactorDisablePostParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the two factor disable post params
func (o *TwoFactorDisablePostParams) SetPassword(password *string) {
	o.Password = password
}

// WriteToRequest writes these params to a swagger request
func (o *TwoFactorDisablePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Password != nil {

		// form param password
		var frPassword string
		if o.Password != nil {
			frPassword = *o.Password
		}
		fPassword := frPassword
		if fPassword != "" {
			if err := r.SetFormParam("password", fPassword); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
