// Code generated by go-swagger; DO NOT EDIT.

package follow_requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owu-one/gotosocial-sdk/models"
)

// GetOutgoingFollowRequestsReader is a Reader for the GetOutgoingFollowRequests structure.
type GetOutgoingFollowRequestsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOutgoingFollowRequestsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOutgoingFollowRequestsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOutgoingFollowRequestsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetOutgoingFollowRequestsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOutgoingFollowRequestsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetOutgoingFollowRequestsNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOutgoingFollowRequestsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/follow_requests/outgoing] getOutgoingFollowRequests", response, response.Code())
	}
}

// NewGetOutgoingFollowRequestsOK creates a GetOutgoingFollowRequestsOK with default headers values
func NewGetOutgoingFollowRequestsOK() *GetOutgoingFollowRequestsOK {
	return &GetOutgoingFollowRequestsOK{}
}

/*
GetOutgoingFollowRequestsOK describes a response with status code 200, with default header values.

GetOutgoingFollowRequestsOK get outgoing follow requests o k
*/
type GetOutgoingFollowRequestsOK struct {

	/* Links to the next and previous queries.
	 */
	Link string

	Payload []*models.Account
}

// IsSuccess returns true when this get outgoing follow requests o k response has a 2xx status code
func (o *GetOutgoingFollowRequestsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get outgoing follow requests o k response has a 3xx status code
func (o *GetOutgoingFollowRequestsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests o k response has a 4xx status code
func (o *GetOutgoingFollowRequestsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get outgoing follow requests o k response has a 5xx status code
func (o *GetOutgoingFollowRequestsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get outgoing follow requests o k response a status code equal to that given
func (o *GetOutgoingFollowRequestsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get outgoing follow requests o k response
func (o *GetOutgoingFollowRequestsOK) Code() int {
	return 200
}

func (o *GetOutgoingFollowRequestsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsOK %s", 200, payload)
}

func (o *GetOutgoingFollowRequestsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsOK %s", 200, payload)
}

func (o *GetOutgoingFollowRequestsOK) GetPayload() []*models.Account {
	return o.Payload
}

func (o *GetOutgoingFollowRequestsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOutgoingFollowRequestsBadRequest creates a GetOutgoingFollowRequestsBadRequest with default headers values
func NewGetOutgoingFollowRequestsBadRequest() *GetOutgoingFollowRequestsBadRequest {
	return &GetOutgoingFollowRequestsBadRequest{}
}

/*
GetOutgoingFollowRequestsBadRequest describes a response with status code 400, with default header values.

bad request
*/
type GetOutgoingFollowRequestsBadRequest struct {
}

// IsSuccess returns true when this get outgoing follow requests bad request response has a 2xx status code
func (o *GetOutgoingFollowRequestsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get outgoing follow requests bad request response has a 3xx status code
func (o *GetOutgoingFollowRequestsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests bad request response has a 4xx status code
func (o *GetOutgoingFollowRequestsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get outgoing follow requests bad request response has a 5xx status code
func (o *GetOutgoingFollowRequestsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get outgoing follow requests bad request response a status code equal to that given
func (o *GetOutgoingFollowRequestsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get outgoing follow requests bad request response
func (o *GetOutgoingFollowRequestsBadRequest) Code() int {
	return 400
}

func (o *GetOutgoingFollowRequestsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsBadRequest", 400)
}

func (o *GetOutgoingFollowRequestsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsBadRequest", 400)
}

func (o *GetOutgoingFollowRequestsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOutgoingFollowRequestsUnauthorized creates a GetOutgoingFollowRequestsUnauthorized with default headers values
func NewGetOutgoingFollowRequestsUnauthorized() *GetOutgoingFollowRequestsUnauthorized {
	return &GetOutgoingFollowRequestsUnauthorized{}
}

/*
GetOutgoingFollowRequestsUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type GetOutgoingFollowRequestsUnauthorized struct {
}

// IsSuccess returns true when this get outgoing follow requests unauthorized response has a 2xx status code
func (o *GetOutgoingFollowRequestsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get outgoing follow requests unauthorized response has a 3xx status code
func (o *GetOutgoingFollowRequestsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests unauthorized response has a 4xx status code
func (o *GetOutgoingFollowRequestsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get outgoing follow requests unauthorized response has a 5xx status code
func (o *GetOutgoingFollowRequestsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get outgoing follow requests unauthorized response a status code equal to that given
func (o *GetOutgoingFollowRequestsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get outgoing follow requests unauthorized response
func (o *GetOutgoingFollowRequestsUnauthorized) Code() int {
	return 401
}

func (o *GetOutgoingFollowRequestsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsUnauthorized", 401)
}

func (o *GetOutgoingFollowRequestsUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsUnauthorized", 401)
}

func (o *GetOutgoingFollowRequestsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOutgoingFollowRequestsNotFound creates a GetOutgoingFollowRequestsNotFound with default headers values
func NewGetOutgoingFollowRequestsNotFound() *GetOutgoingFollowRequestsNotFound {
	return &GetOutgoingFollowRequestsNotFound{}
}

/*
GetOutgoingFollowRequestsNotFound describes a response with status code 404, with default header values.

not found
*/
type GetOutgoingFollowRequestsNotFound struct {
}

// IsSuccess returns true when this get outgoing follow requests not found response has a 2xx status code
func (o *GetOutgoingFollowRequestsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get outgoing follow requests not found response has a 3xx status code
func (o *GetOutgoingFollowRequestsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests not found response has a 4xx status code
func (o *GetOutgoingFollowRequestsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get outgoing follow requests not found response has a 5xx status code
func (o *GetOutgoingFollowRequestsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get outgoing follow requests not found response a status code equal to that given
func (o *GetOutgoingFollowRequestsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get outgoing follow requests not found response
func (o *GetOutgoingFollowRequestsNotFound) Code() int {
	return 404
}

func (o *GetOutgoingFollowRequestsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsNotFound", 404)
}

func (o *GetOutgoingFollowRequestsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsNotFound", 404)
}

func (o *GetOutgoingFollowRequestsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOutgoingFollowRequestsNotAcceptable creates a GetOutgoingFollowRequestsNotAcceptable with default headers values
func NewGetOutgoingFollowRequestsNotAcceptable() *GetOutgoingFollowRequestsNotAcceptable {
	return &GetOutgoingFollowRequestsNotAcceptable{}
}

/*
GetOutgoingFollowRequestsNotAcceptable describes a response with status code 406, with default header values.

not acceptable
*/
type GetOutgoingFollowRequestsNotAcceptable struct {
}

// IsSuccess returns true when this get outgoing follow requests not acceptable response has a 2xx status code
func (o *GetOutgoingFollowRequestsNotAcceptable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get outgoing follow requests not acceptable response has a 3xx status code
func (o *GetOutgoingFollowRequestsNotAcceptable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests not acceptable response has a 4xx status code
func (o *GetOutgoingFollowRequestsNotAcceptable) IsClientError() bool {
	return true
}

// IsServerError returns true when this get outgoing follow requests not acceptable response has a 5xx status code
func (o *GetOutgoingFollowRequestsNotAcceptable) IsServerError() bool {
	return false
}

// IsCode returns true when this get outgoing follow requests not acceptable response a status code equal to that given
func (o *GetOutgoingFollowRequestsNotAcceptable) IsCode(code int) bool {
	return code == 406
}

// Code gets the status code for the get outgoing follow requests not acceptable response
func (o *GetOutgoingFollowRequestsNotAcceptable) Code() int {
	return 406
}

func (o *GetOutgoingFollowRequestsNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsNotAcceptable", 406)
}

func (o *GetOutgoingFollowRequestsNotAcceptable) String() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsNotAcceptable", 406)
}

func (o *GetOutgoingFollowRequestsNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOutgoingFollowRequestsInternalServerError creates a GetOutgoingFollowRequestsInternalServerError with default headers values
func NewGetOutgoingFollowRequestsInternalServerError() *GetOutgoingFollowRequestsInternalServerError {
	return &GetOutgoingFollowRequestsInternalServerError{}
}

/*
GetOutgoingFollowRequestsInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type GetOutgoingFollowRequestsInternalServerError struct {
}

// IsSuccess returns true when this get outgoing follow requests internal server error response has a 2xx status code
func (o *GetOutgoingFollowRequestsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get outgoing follow requests internal server error response has a 3xx status code
func (o *GetOutgoingFollowRequestsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get outgoing follow requests internal server error response has a 4xx status code
func (o *GetOutgoingFollowRequestsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get outgoing follow requests internal server error response has a 5xx status code
func (o *GetOutgoingFollowRequestsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get outgoing follow requests internal server error response a status code equal to that given
func (o *GetOutgoingFollowRequestsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get outgoing follow requests internal server error response
func (o *GetOutgoingFollowRequestsInternalServerError) Code() int {
	return 500
}

func (o *GetOutgoingFollowRequestsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsInternalServerError", 500)
}

func (o *GetOutgoingFollowRequestsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/follow_requests/outgoing][%d] getOutgoingFollowRequestsInternalServerError", 500)
}

func (o *GetOutgoingFollowRequestsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
