// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAppDeleteParams creates a new AppDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAppDeleteParams() *AppDeleteParams {
	return &AppDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAppDeleteParamsWithTimeout creates a new AppDeleteParams object
// with the ability to set a timeout on a request.
func NewAppDeleteParamsWithTimeout(timeout time.Duration) *AppDeleteParams {
	return &AppDeleteParams{
		timeout: timeout,
	}
}

// NewAppDeleteParamsWithContext creates a new AppDeleteParams object
// with the ability to set a context for a request.
func NewAppDeleteParamsWithContext(ctx context.Context) *AppDeleteParams {
	return &AppDeleteParams{
		Context: ctx,
	}
}

// NewAppDeleteParamsWithHTTPClient creates a new AppDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAppDeleteParamsWithHTTPClient(client *http.Client) *AppDeleteParams {
	return &AppDeleteParams{
		HTTPClient: client,
	}
}

/*
AppDeleteParams contains all the parameters to send to the API endpoint

	for the app delete operation.

	Typically these are written to a http.Request.
*/
type AppDeleteParams struct {

	/* ID.

	   The id of the application to delete.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the app delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppDeleteParams) WithDefaults() *AppDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the app delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the app delete params
func (o *AppDeleteParams) WithTimeout(timeout time.Duration) *AppDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the app delete params
func (o *AppDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the app delete params
func (o *AppDeleteParams) WithContext(ctx context.Context) *AppDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the app delete params
func (o *AppDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the app delete params
func (o *AppDeleteParams) WithHTTPClient(client *http.Client) *AppDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the app delete params
func (o *AppDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the app delete params
func (o *AppDeleteParams) WithID(id string) *AppDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the app delete params
func (o *AppDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AppDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
