// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/owu-one/gotosocial-sdk/models"
)

// AppsGetReader is a Reader for the AppsGet structure.
type AppsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAppsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAppsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAppsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAppsGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewAppsGetNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAppsGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/apps] appsGet", response, response.Code())
	}
}

// NewAppsGetOK creates a AppsGetOK with default headers values
func NewAppsGetOK() *AppsGetOK {
	return &AppsGetOK{}
}

/*
AppsGetOK describes a response with status code 200, with default header values.

AppsGetOK apps get o k
*/
type AppsGetOK struct {

	/* Links to the next and previous queries.
	 */
	Link string

	Payload []*models.Application
}

// IsSuccess returns true when this apps get o k response has a 2xx status code
func (o *AppsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this apps get o k response has a 3xx status code
func (o *AppsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get o k response has a 4xx status code
func (o *AppsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this apps get o k response has a 5xx status code
func (o *AppsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this apps get o k response a status code equal to that given
func (o *AppsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the apps get o k response
func (o *AppsGetOK) Code() int {
	return 200
}

func (o *AppsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetOK %s", 200, payload)
}

func (o *AppsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetOK %s", 200, payload)
}

func (o *AppsGetOK) GetPayload() []*models.Application {
	return o.Payload
}

func (o *AppsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppsGetBadRequest creates a AppsGetBadRequest with default headers values
func NewAppsGetBadRequest() *AppsGetBadRequest {
	return &AppsGetBadRequest{}
}

/*
AppsGetBadRequest describes a response with status code 400, with default header values.

bad request
*/
type AppsGetBadRequest struct {
}

// IsSuccess returns true when this apps get bad request response has a 2xx status code
func (o *AppsGetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps get bad request response has a 3xx status code
func (o *AppsGetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get bad request response has a 4xx status code
func (o *AppsGetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this apps get bad request response has a 5xx status code
func (o *AppsGetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this apps get bad request response a status code equal to that given
func (o *AppsGetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the apps get bad request response
func (o *AppsGetBadRequest) Code() int {
	return 400
}

func (o *AppsGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetBadRequest", 400)
}

func (o *AppsGetBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetBadRequest", 400)
}

func (o *AppsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppsGetUnauthorized creates a AppsGetUnauthorized with default headers values
func NewAppsGetUnauthorized() *AppsGetUnauthorized {
	return &AppsGetUnauthorized{}
}

/*
AppsGetUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type AppsGetUnauthorized struct {
}

// IsSuccess returns true when this apps get unauthorized response has a 2xx status code
func (o *AppsGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps get unauthorized response has a 3xx status code
func (o *AppsGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get unauthorized response has a 4xx status code
func (o *AppsGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this apps get unauthorized response has a 5xx status code
func (o *AppsGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this apps get unauthorized response a status code equal to that given
func (o *AppsGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the apps get unauthorized response
func (o *AppsGetUnauthorized) Code() int {
	return 401
}

func (o *AppsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetUnauthorized", 401)
}

func (o *AppsGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetUnauthorized", 401)
}

func (o *AppsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppsGetNotFound creates a AppsGetNotFound with default headers values
func NewAppsGetNotFound() *AppsGetNotFound {
	return &AppsGetNotFound{}
}

/*
AppsGetNotFound describes a response with status code 404, with default header values.

not found
*/
type AppsGetNotFound struct {
}

// IsSuccess returns true when this apps get not found response has a 2xx status code
func (o *AppsGetNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps get not found response has a 3xx status code
func (o *AppsGetNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get not found response has a 4xx status code
func (o *AppsGetNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this apps get not found response has a 5xx status code
func (o *AppsGetNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this apps get not found response a status code equal to that given
func (o *AppsGetNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the apps get not found response
func (o *AppsGetNotFound) Code() int {
	return 404
}

func (o *AppsGetNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetNotFound", 404)
}

func (o *AppsGetNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetNotFound", 404)
}

func (o *AppsGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppsGetNotAcceptable creates a AppsGetNotAcceptable with default headers values
func NewAppsGetNotAcceptable() *AppsGetNotAcceptable {
	return &AppsGetNotAcceptable{}
}

/*
AppsGetNotAcceptable describes a response with status code 406, with default header values.

not acceptable
*/
type AppsGetNotAcceptable struct {
}

// IsSuccess returns true when this apps get not acceptable response has a 2xx status code
func (o *AppsGetNotAcceptable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps get not acceptable response has a 3xx status code
func (o *AppsGetNotAcceptable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get not acceptable response has a 4xx status code
func (o *AppsGetNotAcceptable) IsClientError() bool {
	return true
}

// IsServerError returns true when this apps get not acceptable response has a 5xx status code
func (o *AppsGetNotAcceptable) IsServerError() bool {
	return false
}

// IsCode returns true when this apps get not acceptable response a status code equal to that given
func (o *AppsGetNotAcceptable) IsCode(code int) bool {
	return code == 406
}

// Code gets the status code for the apps get not acceptable response
func (o *AppsGetNotAcceptable) Code() int {
	return 406
}

func (o *AppsGetNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetNotAcceptable", 406)
}

func (o *AppsGetNotAcceptable) String() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetNotAcceptable", 406)
}

func (o *AppsGetNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppsGetInternalServerError creates a AppsGetInternalServerError with default headers values
func NewAppsGetInternalServerError() *AppsGetInternalServerError {
	return &AppsGetInternalServerError{}
}

/*
AppsGetInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type AppsGetInternalServerError struct {
}

// IsSuccess returns true when this apps get internal server error response has a 2xx status code
func (o *AppsGetInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this apps get internal server error response has a 3xx status code
func (o *AppsGetInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this apps get internal server error response has a 4xx status code
func (o *AppsGetInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this apps get internal server error response has a 5xx status code
func (o *AppsGetInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this apps get internal server error response a status code equal to that given
func (o *AppsGetInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the apps get internal server error response
func (o *AppsGetInternalServerError) Code() int {
	return 500
}

func (o *AppsGetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetInternalServerError", 500)
}

func (o *AppsGetInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/apps][%d] appsGetInternalServerError", 500)
}

func (o *AppsGetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
