// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new tokens API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new tokens API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new tokens API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for tokens API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	TokenInfoGet(params *TokenInfoGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokenInfoGetOK, error)

	TokenInvalidatePost(params *TokenInvalidatePostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokenInvalidatePostOK, error)

	TokensInfoGet(params *TokensInfoGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokensInfoGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
TokenInfoGet gets information about a single token
*/
func (a *Client) TokenInfoGet(params *TokenInfoGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokenInfoGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTokenInfoGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "tokenInfoGet",
		Method:             "GET",
		PathPattern:        "/api/v1/tokens/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TokenInfoGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TokenInfoGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for tokenInfoGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
TokenInvalidatePost invalidates the target token removing it from the database and making it unusable
*/
func (a *Client) TokenInvalidatePost(params *TokenInvalidatePostParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokenInvalidatePostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTokenInvalidatePostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "tokenInvalidatePost",
		Method:             "POST",
		PathPattern:        "/api/v1/tokens/{id}/invalidate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TokenInvalidatePostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TokenInvalidatePostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for tokenInvalidatePost: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	TokensInfoGet sees info about tokens created for by your account

	The items will be returned in descending chronological order (newest first), with sequential IDs (bigger = newer).

The returned Link header can be used to generate the previous and next queries when paging up or down.

Example:

```
<https://example.org/api/v1/tokens?limit=20&max_id=01FC3GSQ8A3MMJ43BPZSGEG29M>; rel="next", <https://example.org/api/v1/tokens?limit=20&min_id=01FC3KJW2GYXSDDRA6RWNDM46M>; rel="prev"
````
*/
func (a *Client) TokensInfoGet(params *TokensInfoGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*TokensInfoGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTokensInfoGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "tokensInfoGet",
		Method:             "GET",
		PathPattern:        "/api/v1/tokens",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TokensInfoGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TokensInfoGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for tokensInfoGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
